///|
pub type MermaidError = @model.MermaidError

///|
pub type Direction = @model.Direction

///|
pub type NodeShape = @model.NodeShape

///|
pub type EdgeStyle = @model.EdgeStyle

///|
pub type MermaidNode = @model.MermaidNode

///|
pub type MermaidEdge = @model.MermaidEdge

///|
pub type MermaidSubgraph = @model.MermaidSubgraph

///|
pub type SequenceParticipantKind = @model.SequenceParticipantKind

///|
pub type SequenceBlockType = @model.SequenceBlockType

///|
pub type SequenceBlockDivider = @model.SequenceBlockDivider

///|
pub type SequenceBlock = @model.SequenceBlock

///|
pub type SequenceNotePosition = @model.SequenceNotePosition

///|
pub type SequenceNote = @model.SequenceNote

///|
pub type SequenceActivationCommand = @model.SequenceActivationCommand

///|
pub type MermaidGraph = @model.MermaidGraph
