///|
type NodeShape = @model.NodeShape

///|
type EdgeStyle = @model.EdgeStyle

///|
type DiagramColors = @model.DiagramColors

///|
type Point = @model.Point

///|
type PositionedNode = @model.PositionedNode

///|
type PositionedEdge = @model.PositionedEdge

///|
type PositionedGroup = @model.PositionedGroup

///|
type PositionedSequenceLifeline = @model.PositionedSequenceLifeline

///|
type PositionedSequenceActivation = @model.PositionedSequenceActivation

///|
type PositionedSequenceBlockDivider = @model.PositionedSequenceBlockDivider

///|
type PositionedSequenceBlock = @model.PositionedSequenceBlock

///|
type PositionedSequenceNote = @model.PositionedSequenceNote

///|
type PositionedGraph = @model.PositionedGraph

///|
type SequenceBlockType = @model.SequenceBlockType
