///|
type MermaidGraph = @model.MermaidGraph

///|
type MermaidNode = @model.MermaidNode

///|
type MermaidEdge = @model.MermaidEdge

///|
type SequenceParticipantKind = @model.SequenceParticipantKind

///|
type SequenceNotePosition = @model.SequenceNotePosition

///|
type SequenceActivationCommand = @model.SequenceActivationCommand

///|
type RenderOptions = @model.RenderOptions

///|
type Point = @model.Point

///|
type PositionedNode = @model.PositionedNode

///|
type PositionedEdge = @model.PositionedEdge

///|
type PositionedSequenceLifeline = @model.PositionedSequenceLifeline

///|
type PositionedSequenceActivation = @model.PositionedSequenceActivation

///|
type PositionedSequenceBlockDivider = @model.PositionedSequenceBlockDivider

///|
type PositionedSequenceBlock = @model.PositionedSequenceBlock

///|
type PositionedSequenceNote = @model.PositionedSequenceNote

///|
type PositionedGraph = @model.PositionedGraph
