///|
type MermaidGraph = @model.MermaidGraph

///|
type MermaidNode = @model.MermaidNode

///|
type MermaidEdge = @model.MermaidEdge

///|
type MermaidSubgraph = @model.MermaidSubgraph

///|
type Direction = @model.Direction

///|
type NodeShape = @model.NodeShape

///|
type EdgeStyle = @model.EdgeStyle

///|
type AsciiRenderOptions = @model.AsciiRenderOptions

///|
type RenderOptions = @model.RenderOptions

///|
type Point = @model.Point

///|
type PositionedNode = @model.PositionedNode

///|
type PositionedEdge = @model.PositionedEdge

///|
type PositionedGroup = @model.PositionedGroup

///|
type PositionedGraph = @model.PositionedGraph

///|
type PositionedSequenceLifeline = @model.PositionedSequenceLifeline

///|
type PositionedSequenceActivation = @model.PositionedSequenceActivation

///|
type PositionedSequenceBlockDivider = @model.PositionedSequenceBlockDivider

///|
type PositionedSequenceBlock = @model.PositionedSequenceBlock

///|
type PositionedSequenceNote = @model.PositionedSequenceNote

///|
type SequenceParticipantKind = @model.SequenceParticipantKind

///|
type SequenceBlockType = @model.SequenceBlockType

///|
type SequenceBlockDivider = @model.SequenceBlockDivider

///|
type SequenceBlock = @model.SequenceBlock

///|
type SequenceNotePosition = @model.SequenceNotePosition

///|
type SequenceNote = @model.SequenceNote

///|
type SequenceActivationCommand = @model.SequenceActivationCommand
