///|
type MermaidError = @model.MermaidError

///|
type Direction = @model.Direction

///|
type EdgeStyle = @model.EdgeStyle

///|
type MermaidNode = @model.MermaidNode

///|
type MermaidEdge = @model.MermaidEdge

///|
type MermaidSubgraph = @model.MermaidSubgraph

///|
type SequenceParticipantKind = @model.SequenceParticipantKind

///|
type SequenceBlockType = @model.SequenceBlockType

///|
type SequenceBlockDivider = @model.SequenceBlockDivider

///|
type SequenceBlock = @model.SequenceBlock

///|
type SequenceNotePosition = @model.SequenceNotePosition

///|
type SequenceNote = @model.SequenceNote

///|
type SequenceActivationCommand = @model.SequenceActivationCommand

///|
type MermaidGraph = @model.MermaidGraph
